
[WorldGen]
	#Whether or not the full grass block should turn vanilla grass into full grass (like how dirt turns into grass)
	invasive_grass = true

[Entities]
	#Chance of Teletubby transforming into zombie Teletubby
	#Range: 1 ~ 100
	transformation_probability = 25

[Food]
	#Range: 1 ~ 100
	toast_hunger = 2
	#Range: 1 ~ 100
	custard_hunger = 5
	#Range: 1.0 ~ 100.0
	custard_saturation = 1.5
	#Range: 1.0 ~ 100.0
	toast_saturation = 1.0

